feature(whl): add code demo for lm-env
opendilab/PPOxFamily pull request #94
Opened 2023-09-20 05:34 UTC by kxzxvbk

2023-10-06 16:29 UTC, nighood commented on chapter7_tricks/lm_env.py
> +from transformers import GPT2Tokenizer, GPT2LMHeadModel
When I looked at this code example, I was mainly not clear about the use of GPT2 related classes (sorry for some problems using huddingface). For example, what does the output of the "transformers.GPT2LMHeadModel.generate" method look like. So maybe here can be added a link like this: https://huggingface.co/transformers/v3.0.2/model_doc/gpt2.html#gpt2lmheadmodel

2023-10-08 03:42 UTC, PaParaZz1 requested changes

2023-10-08 03:42 UTC, PaParaZz1 commented on chapter7_tricks/lm_env.py
> +        Initialize TextHistory.
overview

2023-10-08 03:42 UTC, PaParaZz1 commented on chapter7_tricks/lm_env.py
> +        Arguments:
also use **

2023-10-08 03:42 UTC, PaParaZz1 commented on chapter7_tricks/lm_env.py
> +        args:
Arguments

2023-10-08 03:42 UTC, PaParaZz1 commented on chapter7_tricks/lm_env.py
> +        Generate responses for a list of query tensors.
Overview

2023-10-08 03:42 UTC, PaParaZz1 commented on chapter7_tricks/lm_env.py
> +        query_tensors = query_tensors.unsqueeze(0)
add more comments

2023-10-08 03:42 UTC, PaParaZz1 commented on chapter7_tricks/lm_env.py
> +if __name__ == '__main__':
provide some input examples

2023-10-08 03:43 UTC, PaParaZz1 requested changes

2023-10-08 03:43 UTC, PaParaZz1 commented on chapter7_tricks/lm_env.py
> +        self.current_device = self.model.device
define observartion space, action space and reward space

2023-10-09 11:24 UTC, PaParaZz1 approved these changes

2023-10-09 11:24 UTC, merged